### ISSUE TITLE
[Genetics] Please add tooltips and recipie links in genetics machines ingame

### ISSUE THREAD

**Issue by tjsd** [ReneMuetti/binnie-mods-2.0#3]
You should add (in tab mode or just hover over) valid inputs and outputs to tooltip on the machines. I struggle to remember the correct input and output for the different type of growth medium, bacteria, polemeryized and so on. Also NEI integration for recipies is higly needed.

**Comment by ReneMuetti** [comment]
Let me give you just the translation. Binnie is the developer. This notice should be sent to him. So far he has not responded, I've opened a repo here. He has only the English version of the language integrated in the MOD.

Link: https://bitbucket.org/binnie567/binnie-mods/issues
